### ISSUE TITLE
[SUG] [CORE] Войс в табе

### ISSUE THREAD

**Issue by zm-stoner** [deinferno/rmzs-issues#18]
Я хочу видеть маленькую иконку громкоговорителя в табе, которая будет появляться рядом с кнопкой сердечка, мута, и мута в чате. А появляться она будет тогда, когда игрок будет что-то говорить в войс. Зачем это нужно? Всё очень просто.

Я заебался выискивать пиздюков в табе дабы их замутить, они высерают всякую хуиту которая абсолютно бесполезная по отношению к геймплею. Но выискивать конкретного пиздюка в табе из 80 рыл не очень приятно и быстро.

**Comment by deinferno** [comment]
Добавлено, теперь иконка голоса в табе меняет цвет на зеленый при активаций войса
