### ISSUE TITLE
[BUG] [SUG] [ZS] Возрождение на сигилах

### ISSUE THREAD

**Issue by zm-stoner** [deinferno/rmzs-issues#21]
Было 3 сигила. Первый был сломан. Второй был нормальный. Третий расхуяривали дюжина бомжей.
 Мне получилось убить 4 идиотов, и по идее я должен был появиться на втором, но появился на третьем и сразу же умер.

**Comment by deinferno** [comment]
Теперь римиры спавняться на сигиле который был задамажен самым давним
