### ISSUE TITLE
[SUG][ZS] Zban убрать ворону

### ISSUE THREAD

**Issue by snipersir** [deinferno/rmzs-issues#26]
Убрать ворону для Zban'неных игроков, переводить сразу в режим свободного наблюдения. Этот полный Пэ с наблюдением от вороны - себе дороже. 1: у вороны взгляд камеры проходит через центр тела, что не даст адекватно смотреть вверх, с учетом что ворона бегает по поверхности то это ад. 2: невозможно быстро наблюдать за выжившими/раундом в целом от того что ворона имеет коллизию. 3: ворона может мешать игрокам напрямую - если нацепить км шапок и сесть в прицел кейда - у выживших а - сгорит жопа, б - уйдут птр, в - не пройдут удары милишкой.

Оставьте камеру. Джетбум спорол херню сделав такой збан.

**Comment by dexter975** [comment]
Facepalm
