### ISSUE TITLE
[BUG] Застревание в пропах

### ISSUE THREAD

**Issue by zm-stoner** [deinferno/rmzs-issues#3]
Если над пропом нету земли - нельзя войти в фазирование. Вот так вот я и застрял на целую волну пока меня не убили.

![20190307235643_1](https://user-images.githubusercontent.com/48218617/53992429-7c89f980-4135-11e9-858b-8536be225575.jpg)
![20190307235647_1](https://user-images.githubusercontent.com/48218617/53992433-7e53bd00-4135-11e9-9e81-f0c5019f891d.jpg)

**Comment by deinferno** [comment]
Формально ты был в воздухе когда не мог нажать Z?

**Comment by zm-stoner** [comment]
Я проходил через кейд в окне, а когда над моими ногами не оказалось земли - я застрял в пропе. Там уже в фазирование обратно зайти нельзя было.
