### ISSUE TITLE
[BUG][ZS] Flesh creeper model is broken

### ISSUE THREAD

**Issue by snipersir** [deinferno/rmzs-issues#30]
После обновы сломалась модель крипера, Теперь натыкаясь на людей он провоцирует застрявание, причем намертво, до смерти крипера. Так же им можно теперь через стены блочить людей, если те тонкие(понятно как умерло 2 человека застрявших на месте на карте zs_night_cottage, когда их ничего не блочило в комнате).

**Comment by Headshotz** [comment]
This is seem ShouldCollide hook issue. You can try again now.

**Comment by deinferno** [comment]
Closing for now
