### ISSUE TITLE
[BUG][ZS] Heavy strikes // Тяжелые удары

### ISSUE THREAD

**Issue by snipersir** [deinferno/rmzs-issues#33]
1) Perk Heavy Strikes has an incorrect description. As it turned out, it works, if the weapon has at least some kind of knockback.
1.) Перк Тяжелые удары имеет неправильное описание. Как выяснилось, он срабатывает, если у оружия есть хоть какое-то отбрасывание.

2) The reverse 8% damage bypasses Steel Blood's ability to + 50% damage absorption when the total absorption> = 100% damage absorption. As a result, it reduces health.
2.) Обратный 8% урон обходит способность Стальной крови к +50% поглощению урона, когда суммарное поглощение >=100% поглощения урона. Как итог, он уменьшает здоровье.

**Comment by deinferno** [comment]
Добавлена пометка к описанию
