### ISSUE TITLE
[BUG][ZS] Мины имеют коллизию

### ISSUE THREAD

**Issue by snipersir** [deinferno/rmzs-issues#36]
Мины минометов, как и все остальные установки, имеют коллизию для ударов. Не ясно с чего, но теперь море ретардов стало выкупать минометы и ставить мины не на внутреннюю сторону дверного проема/корридора, а на блять обрамление проема причем туда, где нужно бить/стрелять. Уберите коллизию. А лучше сделать их полупрозрачными для остальных игроков + лазерку отображать только для зомбов и для клиента

**Comment by deinferno** [comment]
Мины теперь полупрозрачные и без лазера для своей тимы (если зажать SHIFT можно посмотреть), теперь у мины коллизия как у деплояблов.
