### ISSUE TITLE
[SUG] [ZS] WaGoN Balance

### ISSUE THREAD

**Issue by Kpyxa** [deinferno/rmzs-issues#4]
Надо кароч убрать нахуй весь рандом из скиллов и оружия.
Например поставить срабатывание рипер стаков у глока по набору опр. кол-ва урона либо 1 стак за убийство. Со скиллом шеф-повар то-же самое, с выпаданием еды из ресапла еще.
![20190309121120_1](https://user-images.githubusercontent.com/48378742/54068872-fd024480-4272-11e9-82eb-6fda1a6106ee.jpg)
Еще неплохо было бы сделать такое-же объяснение эффектов как на санрасте.
![20190309121245_1](https://user-images.githubusercontent.com/48378742/54068881-14413200-4273-11e9-8448-2eae0df60388.jpg)
Насчет шеф-повара - выдавание хавки либо за нанесение опр кол-ва урона (100-150) либо тупо за убийство.
А выдача хавки из ресапла (пока декстер холодильник не ввел) вместо шанса сделать 100% выдачу при взятии патронов, но естественно кулдаун у ресапла увиличится.

**Comment by snipersir** [comment]
100% хавки - это мед саплы с аммы + мед саплы с тринкета Мед процессор. Слишком оп шанс.
