### ISSUE TITLE
[ZS] Складывание чужих деплояблов

### ISSUE THREAD

**Issue by zm-stoner** [deinferno/rmzs-issues#50]
На самом деле ситуаций где это может помешать слишком мало, но вот ночью при малом онлайне это вполне может быть.

Описание: Для складывания чужого деплоябла всегда требуется 4 игроков. Если же живых игроков 4 или меньше то сложить деплоябл может только хозяин по очевидным причинам.

Предложение: 4 живых игроков - 3 требуемых игроков для складывания.
                         3 живых игроков - 2 требуемых игроков для складывания.

**Comment by deinferno** [comment]
Добавлено в коммите 4469806
