### ISSUE TITLE
[BUG] [ZS] Партикли

### ISSUE THREAD

**Issue by zm-stoner** [deinferno/rmzs-issues#54]
Из-за того что у меня отключены партикли, я теперь не вижу зомби газ... Теперь мне нужно развивать телепатические чувства, дабы не зайти в него в процессе побега от зомби... И не нужно мне говорить "включи партикли, долбаёб". Я не для того их выключал, чтобы не видеть зомби-газ и кровь red marrow'а.

**Comment by deinferno** [comment]
Исправлено. Партиклы зомби газа и красного кошмара теперь рендерятся всегда.
