### ISSUE TITLE
[BUG][ZS] Нет задержки переключения у кулаков

### ISSUE THREAD

**Issue by snipersir** [deinferno/rmzs-issues#58]
Задержка удара до полного проигрывания анимации у кулаков сломана, либо отсутствует. Из-за этой параша переключение на кулаки во время бега, или других действий зачастую ведет к случайному удару, от чего идет замедление в ходьбе. Из-за этого косяка, после случайного переключения и случайного последующего удара в никуда, в моем случае, у меня пропала нужная скорость и я наебнулся насмерть на zs_dryfields с водонапорной башни. Почините эту хзерь(кроме случаев со смертельным исходом хватает и просто заеба с этого косяка в обычное время вроде маневрирования в кейде и ходьбе, например, у фронтов, либо при работе с инвентарем)

**Comment by Nickolp** [comment]
Всегда качай "сильные удары",и да, эта фича с кулаками часто спасает

**Comment by deinferno** [comment]
Теперь есть
