### ISSUE TITLE
[ZS][BUG] Редим в начале раунда

### ISSUE THREAD

**Issue by zm-stoner** [deinferno/rmzs-issues#73]
![20190715063447_1](https://user-images.githubusercontent.com/48218617/61194728-178a7580-a6cc-11e9-94d9-428866e02513.jpg)
![20190715063459_1](https://user-images.githubusercontent.com/48218617/61194730-1bb69300-a6cc-11e9-9d7c-adb81704e89b.jpg)
 Ок, я хочу знать, какого хуя эта ебанная система не редимает тех, кто превысил начальное кол-во зомби? Теперь появился тут один мудак, который перезаходит на сервер в начале игры и оказывается на стороне зомби, и после начала он не редимается, и пользуется этим в свою пользу, стабильно и регулярно сливая игры, устанавливая несты, расхуяривая всех древним найтмаром и прочее. Естевственно, наказать его за это нельзя, ибо это дыра в системе.

**Comment by dexter975** [comment]
wtf?
