### ISSUE TITLE
[BUG][ZS] ???

### ISSUE THREAD

**Issue by zm-stoner** [deinferno/rmzs-issues#75]
![20190725110840_1](https://user-images.githubusercontent.com/48218617/61857488-f1838300-aecc-11e9-886b-25594170e0e0.jpg)

Без какой-либо на то видимой причины в начале игры у меня был открыт инвентарь, причём закрыть его невозможно. Я пробовал писать в консоль -alt1, -alt2, +alt1, +alt2, ничего не помогло. Так-же я не мог двигаться, открыть чат и подобное. 

И ДАЖЕ КОГДА УМЕР:

![20190725111334_1](https://user-images.githubusercontent.com/48218617/61857686-4626fe00-aecd-11e9-8e21-72088e90d08d.jpg)

![20190725111338_1](https://user-images.githubusercontent.com/48218617/61857689-49ba8500-aecd-11e9-8bdb-a707c3c3aee5.jpg)

**Comment by dexter975** [comment]
это случается если ты сделал "альт-таб" в смену карты. -walk может помочь в таких ситуациях
