### ISSUE TITLE
[BUG] [MAP] Сигил в браше

### ISSUE THREAD

**Issue by zm-stoner** [deinferno/rmzs-issues#8]
zs_development_v1
Из этого сигила нельзя выбраться
![20190309235058_1](https://user-images.githubusercontent.com/48218617/54077803-5a73b100-42c6-11e9-933e-9c9f958aa321.jpg)
![20190309235227_1](https://user-images.githubusercontent.com/48218617/54077817-72e3cb80-42c6-11e9-94c9-54bbb5bd4530.jpg)

**Comment by dexter975** [comment]
больше не оставляй проблемы связанные с картами на гитхабе.
