### ISSUE TITLE
[BUG] Хиты по мясу

### ISSUE THREAD

**Issue by zm-stoner** [deinferno/rmzs-issues#9]
![20190310015554_1](https://user-images.githubusercontent.com/48218617/54078912-f22eca80-42d9-11e9-8217-a9127d1310d0.jpg)
Если ударить, к примеру, эартшейкером (ПКМ) по куску мяса, то его эффект не произойдет. Часто бывает что зомби рвёт в мясо, и иногда можно промахнуться. Иногда модели мяса слишком большие.

**Comment by dexter975** [comment]
это не баг. у этой абилки есть условие: игрок должен ударить именно по земле/полу!

**Comment by zm-stoner** [comment]
Это мясо должно был побочным интерьером, часть декора, оно не должно воздействовать на геймплей. Это глупо когда такой здоровенный молот не может пробить кусочек мяса

**Comment by dexter975** [comment]
здоровенный молот таки уничтожает этот кусок мяса!
Данная ситуация не будет рассматриваться как баг!
